{% set name = "pytest-order" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-order-{{ version }}.tar.gz
  sha256: 044e4c90d86895792e6da7577df7fed6440bd59ee593374f9252679a252d8eaa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pytest >=3.7
  run:
    - pytest >=3.7
    - python >=3.6

test:
  imports:
    - pytest_order
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrbean-bremen/pytest-order
  summary: pytest plugin to run your tests in a specific order
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
